[project]
name = "sentinel-sim-backend"
version = "0.1.0"
description = "SIEM Control Plane API - Sentinel-Sim"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Lead Architect", email = "admin@sentinel-sim.local" }
]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"